/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CODE_FONT_SIZE_MAX: typeof import('./stores/ui').CODE_FONT_SIZE_MAX
  const CODE_FONT_SIZE_MIN: typeof import('./stores/ui').CODE_FONT_SIZE_MIN
  const COMMIT_COLUMN_DEFAULTS: typeof import('./stores/ui').COMMIT_COLUMN_DEFAULTS
  const DEFAULT_CODE_FONT_SIZE: typeof import('./stores/ui').DEFAULT_CODE_FONT_SIZE
  const DEFAULT_DIFF_VIEW_MODE: typeof import('./stores/ui').DEFAULT_DIFF_VIEW_MODE
  const DEFAULT_FILE_VIEW_MODE: typeof import('./stores/ui').DEFAULT_FILE_VIEW_MODE
  const DEFAULT_FORMAT_BEFORE_GENERATE: typeof import('./stores/ui').DEFAULT_FORMAT_BEFORE_GENERATE
  const DEFAULT_SHOW_ENTIRE_FILE: typeof import('./stores/ui').DEFAULT_SHOW_ENTIRE_FILE
  const DEFAULT_THEME: typeof import('./stores/ui').DEFAULT_THEME
  const DEFAULT_WORKSPACE: typeof import('./stores/workspace').DEFAULT_WORKSPACE
  const FONT_SIZE_OPTIONS: typeof import('./stores/ui').FONT_SIZE_OPTIONS
  const REFRESH_INTERVAL_OPTIONS: typeof import('./stores/ui').REFRESH_INTERVAL_OPTIONS
  const REPO_TAB_COLOR_OPTIONS: typeof import('./stores/ui').REPO_TAB_COLOR_OPTIONS
  const SHORTCUTS: typeof import('./utils/shortcuts').SHORTCUTS
  const TOAST_DURATION: typeof import('./stores/uiTransient').TOAST_DURATION
  const ZOOM_OPTIONS: typeof import('./stores/ui').ZOOM_OPTIONS
  const buildPrefix: typeof import('./utils/virtual').buildPrefix
  const buildTree: typeof import('./utils/fileTree').buildTree
  const computeLineStates: typeof import('./utils/highlight').computeLineStates
  const computed: typeof import('vue').computed
  const confirmDialog: typeof import('./utils/confirm').confirmDialog
  const defineEmits: typeof import('vue').defineEmits
  const defineProps: typeof import('vue').defineProps
  const defineStore: typeof import('pinia').defineStore
  const detectMovedLines: typeof import('./utils/highlight').detectMovedLines
  const flattenTree: typeof import('./utils/fileTree').flattenTree
  const formatCommitDate: typeof import('./utils/format').formatCommitDate
  const formatDatePattern: typeof import('./utils/format').formatDatePattern
  const formatDateTime: typeof import('./utils/format').formatDateTime
  const formatShortDate: typeof import('./utils/format').formatShortDate
  const highlightDiffLines: typeof import('./utils/highlight').highlightDiffLines
  const highlightLine: typeof import('./utils/highlight').highlightLine
  const highlightLineAt: typeof import('./utils/highlight').highlightLineAt
  const indexAtOffset: typeof import('./utils/virtual').indexAtOffset
  const inject: typeof import('vue').inject
  const intraLineRange: typeof import('./utils/highlight').intraLineRange
  const isMac: typeof import('./utils/shortcuts').isMac
  const isWhitespaceOnlyChange: typeof import('./utils/highlight').isWhitespaceOnlyChange
  const keysFor: typeof import('./utils/shortcuts').keysFor
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onMounted: typeof import('vue').onMounted
  const onUnmounted: typeof import('vue').onUnmounted
  const promptDialog: typeof import('./utils/prompt').promptDialog
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const ref: typeof import('vue').ref
  const renderDiffContent: typeof import('./utils/highlight').renderDiffContent
  const resolveCheckoutMode: typeof import('./utils/checkout').resolveCheckoutMode
  const storeToRefs: typeof import('pinia').storeToRefs
  const switchDialog: typeof import('./utils/switch').switchDialog
  const toRefs: typeof import('vue').toRefs
  const useAiStore: typeof import('./stores/ai').useAiStore
  const useAuthStore: typeof import('./stores/auth').useAuthStore
  const useConfirmStore: typeof import('./stores/confirm').useConfirmStore
  const usePromptStore: typeof import('./stores/prompt').usePromptStore
  const useRepoStore: typeof import('./stores/repo').useRepoStore
  const useSwitchStore: typeof import('./stores/switch').useSwitchStore
  const useSyncStore: typeof import('./stores/sync').useSyncStore
  const useUiStore: typeof import('./stores/ui').useUiStore
  const useUiTransientStore: typeof import('./stores/uiTransient').useUiTransientStore
  const useWorkspaceStore: typeof import('./stores/workspace').useWorkspaceStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const windowFor: typeof import('./utils/virtual').windowFor
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ConfirmOptions, ConfirmRequest } from './stores/confirm'
  import('./stores/confirm')
  // @ts-ignore
  export type { PromptOptions, PromptResult, PromptRequest } from './stores/prompt'
  import('./stores/prompt')
  // @ts-ignore
  export type { RepoTab } from './stores/repo'
  import('./stores/repo')
  // @ts-ignore
  export type { SwitchRequest } from './stores/switch'
  import('./stores/switch')
  // @ts-ignore
  export type { Theme, AiCommitMode, RepoTabColor, CommitColumn, DiffViewMode, FileViewMode, ThemeOption } from './stores/ui'
  import('./stores/ui')
  // @ts-ignore
  export type { ToastKind, NotifyOptions } from './stores/uiTransient'
  import('./stores/uiTransient')
  // @ts-ignore
  export type { WorkspaceSession } from './stores/workspace'
  import('./stores/workspace')
  // @ts-ignore
  export type { FileNode, TreeRow } from './utils/fileTree'
  import('./utils/fileTree')
  // @ts-ignore
  export type { LineRenderContext } from './utils/highlight'
  import('./utils/highlight')
  // @ts-ignore
  export type { ShortcutDef } from './utils/shortcuts'
  import('./utils/shortcuts')
}
